restaurants = [
    {"Name": "Thai Table", "Healthy": False, "Sit down": False},
    {"Name": "Bo's", "Healthy": True, "Sit down": False},
    {"Name": "Parrilla", "Healthy": False, "Sit down": False},
    {"Name": "El Sancho", "Healthy": False, "Sit down": False},
    {"Name": "Mother's", "Healthy": True, "Sit down": False},
    {"Name": "Brother Jon's", "Healthy": False, "Sit down": False},
    {"Name": "10 Barrel", "Healthy": False, "Sit down": True},
    {"Name": "Spork", "Healthy": True, "Sit down": False},
    {"Name": "Active Culture", "Healthy": True, "Sit down": False},
    {"Name": "Croutons", "Healthy": True, "Sit down": False},
    {"Name": "Jackson's Corner", "Healthy": True, "Sit down": False},
    {"Name": "Bangers & Brews", "Healthy": False, "Sit down": False},
    {"Name": "Cheba Hut", "Healthy": True, "Sit down": True},
    {"Name": "Life & Time", "Healthy": True, "Sit down": False},
    {"Name": "McMenamins", "Healthy": True, "Sit down": False},
    {"Name": "Plankers", "Healthy": False, "Sit down": False},
    {"Name": "Valentines", "Healthy": False, "Sit down": False},
    {"Name": "Cafe Sintra", "Healthy": True, "Sit down": False},
    {"Name": "Wild Rose", "Healthy": True, "Sit down": False},
    {"Name": "BTBS", "Healthy": True, "Sit down": False},
    {"Name": "Miyagi Ramen", "Healthy": False, "Sit down": True},
    {"Name": "Brown Owl", "Healthy": False, "Sit down": True},
    {"Name": "Crosscut", "Healthy": True, "Sit down": True},
    {"Name": "Podski", "Healthy": True, "Sit down": True},
    {"Name": "The Lot", "Healthy": False, "Sit down": True},
    {"Name": "The Grove", "Healthy": True, "Sit down": True},
    {"Name": "Cafe Yumm", "Healthy": True, "Sit down": False},
    {"Name": "Kona Mix Plate", "Healthy": True, "Sit down": True},
    {"Name": "Sunriver Brewing", "Healthy": True, "Sit down": True},
    {"Name": "Dump City", "Healthy": False, "Sit down": False},
    {"Name": "Super Burrito", "Healthy": False, "Sit down": True},
    {"Name": "Pacific Pizza", "Healthy": False, "Sit down": True},
    {"Name": "Chicken Bonz", "Healthy": False, "Sit down": True},
]